package matlab;

import java.nio.file.Path;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

import params.SystemParams;
import params.WindowManager;

import models.Variable;

/**
 * Classe pour construire les fichiers MATLAB avec les equations
 * @author DEVERDUN Jeremy
 *
 */
public class MatlabBuilder {

	private static final String mainFunctionName = "SEB_model_main";//fichier principal
	private static final String equationsInitialFunctionName = "SEB_model_eqInit";//fichier equation initiales
	private static final String equationsTimeFunctionName = "SEB_model_eqTime";//fichier equation Time
	public static final String unknownLabel = "x";
	public static final String equResultLabel = "equ";
	
	public static MatlabModel buildModel(Path folder, ArrayList<Variable> globalvariables,
			ArrayList<Variable> fixedvariables, ArrayList<Variable> variables) {
		if(!folder.toFile().canWrite()){
			SwingUtilities.invokeLater(new Runnable() {
				
				@Override
				public void run() {
					JDialog.setDefaultLookAndFeelDecorated(true);
					JOptionPane.showMessageDialog(WindowManager.MAINWINDOW,
						    "Can't write into specified directory",
						    "Permission denied",
						    JOptionPane.ERROR_MESSAGE);
				}
			});
			return null;
		}
		
		// create file headers
		String modelHeader = createModelHeader();
		String equationInitialHeader = createEquationInitialHeader();
		String equationTimeHeader = createEquationTimeHeader();
		// create global
		String globalvarcontent = globalVarsDefinition(globalvariables);
		
		
		System.out.println(equationInitialHeader+globalvarcontent);
		return null;
	}
	
	/**
	 * Cree l'entete du fichier principal du modele (du script matlab)
	 * @return
	 */
	private static String createModelHeader() {
		String content = "%% Model script\n%%\n";
		content += "%% This file is the main matlab script for the model\n%%\n";
		content += "%% You can use it as a script\n";
		content += "%% File generated by "+SystemParams.PROGRAM_NAME+" Version : "+SystemParams.VERSION+"\n";
		DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
		Date date = new Date();
		content += "%% Date : "+dateFormat.format(date)+"\n";
		content += "function "+mainFunctionName+"\n";
		return content;
	}

	/**
	 * Cree l'entete du fichier qui contient les equation initiales du modele
	 * @return
	 */
	private static String createEquationInitialHeader() {
		String content = "%% Model function\n%%\n";
		content += "%% This file contains equations for the round of the fsolve\n%%\n";
		content += "%% You should only call this file through "+mainFunctionName+"\n";
		content += "%% File generated by "+SystemParams.PROGRAM_NAME+" Version : "+SystemParams.VERSION+"\n";
		DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
		Date date = new Date();
		content += "%% Date : "+dateFormat.format(date)+"\n";
		content += "function "+equResultLabel+" = "+equationsInitialFunctionName+"("+unknownLabel+")\n";
		return content;
	}

	/**
	 * Cree l'entete du fichier qui contient les equation au cours du temps du modele
	 * @return
	 */
	private static String createEquationTimeHeader() {
		String content = "%% Model function\n%%\n";
		content += "%% This file contains equations for the round of the fsolve\n%%\n";
		content += "%% You should only call this file through "+mainFunctionName+"\n";
		content += "%% File generated by "+SystemParams.PROGRAM_NAME+" Version : "+SystemParams.VERSION+"\n";
		DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
		Date date = new Date();
		content += "%% Date : "+dateFormat.format(date)+"\n";
		content += "function "+equResultLabel+" = "+equationsTimeFunctionName+"("+unknownLabel+")\n";
		return content;
	}

	/**
	 * Cree le contenu des fichiers m concernant les definitions de variables globales
	 * @param globalvariables
	 * @return
	 */
	public static String globalVarsDefinition(ArrayList<Variable> globalvariables){
		String content = "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n";
		content += "%%       Declaring global variables     %%\n";
		content += "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n";
		for(Variable var:globalvariables){
			content += "global "+var.getName()+";\n";
		}
		return content;
	}

}
